### ISSUE TITLE
Deck size on the UI doesn't always update properly

### ISSUE THREAD

**Issue by Jumper706** [DrunkDutch/comp-354#139]
Right after you draw your starting hand it says you have 48 cards but the deck actually has 55

**Comment by DrunkDutch** [comment]
Is it possible that you arent taking into account mulligan draws and rewards?

**Comment by Jumper706** [comment]
I printed out the size of the deck and it was 53 which was correct

**Comment by cclp94** [comment]
Not a defect. 6 Rewards cards and 6 hand cards were taken off the deck which makes it be 60 - 12 = 48
