### ISSUE TITLE
As a user I want the AI to be able to actually play during its turn

### ISSUE THREAD

**Issue by DrunkDutch** [DrunkDutch/comp-354#41]
AI should be able to play basic abilities (requires Energy Cost checking)
Requires player being able to swap pokemon
Requires GUI updates

**Comment by cclp94** [comment]
- [x] AI plays energy on active until active has all its "energy needs" fulfilled, then play energy on benched pokemon (Only 1 energy per turn).
- [x] AI attacks with most powerful attack available in the turn
- [x] AI evolves when possible (regardless if active or not) (Depends on #39)
- [x] AI plays trainer card when possible (regardless if it will be useful or not)

**Comment by cclp94** [comment]
Missing restrict AI attack when not enough energy is placed(done)
