### ISSUE TITLE
Randomizer Test appears to be flaky

### ISSUE THREAD

**Issue by DrunkDutch** [DrunkDutch/comp-354#89]
The [Randomizer Test](https://github.com/DrunkDutch/comp-354/blob/master/src/test/java/com/dmens/pokeno/UtilsTest/RandomizerTest.java) appears to be a little flaky, it passes in local environments but with the merge of the energy card turn limit as seen in this [build](https://circleci.com/gh/DrunkDutch/comp-354/177)

**Comment by JRF27** [comment]
Made the test a bit more robust by running it 10 times and then taking an average of the results. Also reduced the threshold to 5 since the accuracy has increased.

Branch Issue89 was merged into master.
